name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          CURRENT_PATH=$(pwd)
          export PATH=$PATH:$(go env GOPATH)/bin
          git clone https://github.com/meshplus/bitxhub.git
          cd bitxhub && git checkout master
          make prepare
          cd scripts && nohup bash solo.sh &
          sleep 60s
          cd "${CURRENT_PATH}" && mvn -B package --file pom.xml
